//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace agenda.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class appointment
    {
        public int idAppointment { get; set; }

        [DisplayName("Date et heure")]
        [Required]
        public System.DateTime dateHour { get; set; }

        [DisplayName("Sujet")]
        [Required]
        public string subject { get; set; }

        [DisplayName("Courtier")]
        [Required]
        public int idBroker { get; set; }

        [DisplayName("Client")]
        [Required]
        public int idCustomer { get; set; }
    
        public virtual broker broker { get; set; }
        public virtual customer customer { get; set; }
    }
}
